"""Generate the Sveltia CMS configuration (admin/config.yml and admin/index.html) from the folder tree.

The tree is the source of truth: one singleton per section index page, a Policies collection per
section, then (listed after all the Policies) a Regulations collection for every section that has a
regulation.md. Re-run
`boardify cms-config` after adding a section or the first regulation in one.
"""
import json
import re
from pathlib import Path

import frontmatter

SCHEMA = "https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json"
CODE_PATTERN = r"^\d\d\d\d-\d\d$"


def q(value):
    """A YAML double-quoted scalar (JSON strings are valid YAML)."""
    return json.dumps(value, ensure_ascii=False)


def sections(cfg):
    """[(folder name, slug, title, has_regulations)] in order."""
    root = Path(cfg["policies_root"])
    found = []
    for folder in sorted(p for p in root.iterdir() if p.is_dir()):
        m = re.match(r"(\d{4})-(.+)", folder.name)
        if not m:
            continue
        index = folder / "index.md"
        title = frontmatter.load(index).get("title") if index.exists() else m.group(2).title()
        has_regs = any((p / "regulation.md").exists() for p in folder.iterdir() if p.is_dir())
        found.append({"folder": folder.name, "code": m.group(1), "slug": m.group(2), "title": title,
                      "regulations": has_regs})
    return found


def body_fields(indent):
    pad = " " * indent
    return (
        f"{pad}- name: title\n{pad}  label: Title\n{pad}  widget: string\n"
        f"{pad}- name: body\n{pad}  label: Body\n{pad}  widget: richtext\n"
    )


def singleton(name, label, file):
    return (
        f"  - name: {q(name)}\n    label: {q(label)}\n    file: {q(file)}\n    fields:\n"
        + body_fields(6)
    )


def collection(cfg, section, kind):
    """A flat collection for one section and kind, or (section=None) a tree of all sections."""
    plural = "Policies" if kind == "Policy" else "Regulations"
    page = "index" if kind == "Policy" else "regulation"
    root = cfg["policies_root"]
    if section:
        name, label = f"{section['slug']}_{plural.lower()}", f"{plural} – {section['code']} {section['title']}"
        folder, depth = f"{root}/{section['folder']}", 2
    else:
        name, label = plural.lower(), plural
        folder, depth = root, 3  # <section>/<code>-<slug>/<page>
    return f"""  - name: {q(name)}
    label: {q(label)}
    label_singular: {kind}
    folder: {q(folder)}
    nested:
      depth: {depth}
      subfolders: false
    path: '{{{{code}}}}-{{{{title}}}}/{page}'
    filter: {{field: kind, value: {kind}}}
    summary: '{{{{code}}}} {{{{title}}}}'
    fields:
      - name: code
        label: Code
        widget: string
        pattern: [{q(CODE_PATTERN)}, "Must be in the ####-## code format"]
      - name: title
        label: Title
        widget: string
      - name: kind
        label: Kind
        widget: hidden
        default: {kind}
      - name: updated
        label: Updated
        widget: hidden
        default: '{{{{datetime}}}}'
      - name: reference
        label: Reference
        widget: text
        required: false
      - name: body
        label: Content
        widget: markdown
"""


def build_config(cfg):
    cms = cfg["cms"]
    for required in ("repo", "base_url"):
        if not cms[required]:
            raise SystemExit(f"[tool.boardify.cms] {required} is required for cms-config")
    root = Path(cfg["policies_root"])
    docs_root = root.parent
    out = [
        f"# yaml-language-server: $schema={SCHEMA}\n",
        "# GENERATED by `boardify cms-config` from the content folders; edit the folders or",
        "# [tool.boardify.cms] in pyproject.toml, not this file.\n",
        (f"backend:\n  name: github\n  repo: {q(cms['repo'])}\n  branch: {q(cms['branch'])}\n"
        f"  base_url: {q(cms['base_url'])}\n  commit_messages:\n"
        "    create: Create {{slug}}\n    update: Update {{slug}}\n    delete: Delete {{slug}}\n"
        "    uploadMedia: Upload {{path}}\n    deleteMedia: Delete {{path}}\n"
        "  cms_label_prefix: boardify/\n"),
        (f"logo:\n  src: {q(cms['logo'])}\napp_title: {q(cms['app_title'])}\n"
        "publish_mode: editorial_workflow\n"
        f"media_folder: {q(cms['media_folder'])}\npublic_folder: {q(cms['public_folder'])}\n"
        "editor:\n  preview: false\n"),
        "singletons:\n",
    ]
    secs = sections(cfg)
    if (docs_root / "index.md").exists():
        out.append(singleton("home", "Home Page", f"{docs_root.as_posix()}/index.md"))
    for s in secs:
        out.append(singleton(f"{s['slug']}_page", f"{s['title']} Page", f"{root.as_posix()}/{s['folder']}/index.md"))
    out.append("collections:\n")
    if cms["layout"] == "tree":
        out.append(collection(cfg, None, "Policy"))
        if any(s["regulations"] for s in secs):
            out.append(collection(cfg, None, "Regulation"))
    elif cms["layout"] == "sections":
        for s in secs:
            out.append(collection(cfg, s, "Policy"))
        for s in secs:
            if s["regulations"]:
                out.append(collection(cfg, s, "Regulation"))
    else:
        raise SystemExit('[tool.boardify.cms] layout must be "sections" or "tree"')
    return "".join(x if x.endswith("\n") else x + "\n" for x in out)


def build_index(cfg):
    cms = cfg["cms"]
    if not cms["sveltia_version"]:
        raise SystemExit("[tool.boardify.cms] sveltia_version is required (pin an exact version)")
    src = f"https://unpkg.com/@sveltia/cms@{cms['sveltia_version']}/dist/sveltia-cms.js"
    integrity = f' integrity="{cms["sveltia_integrity"]}" crossorigin="anonymous"' if cms["sveltia_integrity"] else ""
    return f"""<!DOCTYPE html>
<!-- GENERATED by `boardify cms-config`; edit [tool.boardify.cms] in pyproject.toml, not this file. -->
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex" />
    <title>{cms['app_title']}</title>
  </head>
  <body>
    <script src="{src}"{integrity}></script>
    <script>
      CMS.registerEventListener({{
        name: 'preSave',
        handler: ({{ entry }}) => {{
          const data = entry.get('data');
          return data.has('updated') ? data.set('updated', new Date().toISOString()) : data;
        }},
      }});
    </script>
  </body>
</html>
"""


def main(cfg, check=False):
    cms = cfg["cms"]
    targets = {Path(cms["config_path"]): build_config(cfg), Path(cms["index_path"]): build_index(cfg)}
    stale = [p for p, text in targets.items() if not p.exists() or p.read_text() != text]
    if check:
        for p in stale:
            print(f"out of date: {p} (run `boardify cms-config`)")
        return 1 if stale else 0
    for p, text in targets.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
        print(f"wrote {p}")
    return 0
