# This takes Boardify project status changes and syncs them with the Github project labels.
name: Sync Project Status
on:
  pull_request:
    paths:
      - 'content/policies/**'
    types:
      - labeled
jobs:
  update-status:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PROJECT_STATUS_MANAGEMENT_SECRET }}
      PR_ID: ${{ github.event.pull_request.node_id }}
      PROJECT_ID: ${{vars.PROJECT_ID}}
    steps:
      - name: Get Project ItemID from PR NodeID
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectV2ItemById.item.id')"
          echo 'ITEM_ID='$item_id >> $GITHUB_ENV
      - name: Update if Draft
        if: ${{ contains(github.event.pull_request.labels.*.name, 'boardify/draft') }}
        run: |
          gh project item-edit --id ${{ env.ITEM_ID }} --field-id ${{vars.STATUS_ID}} --single-select-option-id ${{vars.SSO_ID_DRAFT}} --project-id ${{env.PROJECT_ID}}
      - name: Update if Review
        if: ${{ contains(github.event.pull_request.labels.*.name, 'boardify/pending_review') }}
        run: |
          gh project item-edit --id ${{ env.ITEM_ID }} --field-id ${{vars.STATUS_ID}} --single-select-option-id ${{vars.SSO_ID_REVIEW}} --project-id ${{env.PROJECT_ID}}
      - name: Update if Ready
        if: ${{ contains(github.event.pull_request.labels.*.name, 'boardify/pending_publish') }}
        run: |
          gh project item-edit --id ${{ env.ITEM_ID }} --field-id ${{vars.STATUS_ID}} --single-select-option-id ${{vars.SSO_ID_READY}} --project-id ${{env.PROJECT_ID}}
